
INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK,  SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Decepticon', 1,5,6,6,9,'Decepticon',7,10,2,8,'D' );

    INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK, SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Decepticon', 2,5,7,8,9,'Decepticon 1',2,2,2,2,'D' );

    INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK, SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Decepticon', 3,4,6,6,7,'Decepticon 2',3,3,2,8,'D' );

    INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK, SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Autobot', 4,4,9,7,10,'Autobot',4,4,2,3,'A' );
    INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK, SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Autobot', 5,9,9,9,9,'Autobot 1',9,9,9,9,'A' );
    INSERT INTO
    TRANSFORMER
    (DTYPE, ID, COURAGE, ENDURANCE, FIREPOWER, INTELLIGENCE, NAME, RANK, SKILL, SPEED, STRENGTH,TYPE)
    VALUES ('Autobot', 6,1,1,3,3,'Autobot 2',1,3,2,1,'A' );